<<<<<<< HEAD
all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: //wsl$/Ubuntu-18.04/usr/id_rsa
children:
    db_user: usr
    db_password: pwd
  children:
    prod:
=======
all:
  vars:
    ansible_user: centos
    ansible_ssh_private_key_file: //wsl$/Ubuntu-18.04/usr/id_rsa
children:
    db_user: usr
    db_password: pwd
  children:
    prod:
>>>>>>> e7c348e... fin du tp3
      hosts: melinaprune.mendugamvogo.takima.cloud